### ISSUE TITLE
bhom.xyz: update installer to 2.4.beta.0

### ISSUE THREAD

**Issue by al-fisher** [BHoM/bhom.github.io#27]

**Comment by epignatelli** [comment]
Thanks @al-fisher I can take care of this, @FraserGreenroyd !

Just in case of cataclysms, https://github.com/BHoM/bhom.github.io/wiki/How-to-update-the-installer-link

**Comment by FraserGreenroyd** [comment]
I'm going to do this today as discussed with @al-fisher just an FYI @epignatelli :smile:

**Comment by al-fisher** [comment]
Thanks @FraserGreenroyd

**Comment by al-fisher** [comment]
@FraserGreenroyd - just realised the hyperlink text on the front page not updated! Sorry - my bad also on review 🤦‍♂ 
I will push update shortly to fix

**Comment by FraserGreenroyd** [comment]
After I followed @epignatelli wiki and everything >.< I do apologise - if you're happy to push an update @al-fisher I can also do it from here for you to review if you'd rather?

**Comment by al-fisher** [comment]
Thanks! No problem - both culpable! 😄
I am already on it - so will push update in a min. Train wifi allowing!!

**Comment by FraserGreenroyd** [comment]
I'm tethered to my phone - I'm not sure that connection is much better! But am poised for the push :smile:

**Comment by epignatelli** [comment]
Hi all!! Apologies for not mentioning it in the wiki, it should've been there in the first place.
I just added it for the future! https://github.com/BHoM/bhom.github.io/wiki/How-to-update-the-installer-link
