### ISSUE TITLE
Provide means to access and download alpha daily builds

### ISSUE THREAD

**Issue by al-fisher** [BHoM/bhom.github.io#28]
To be implemented following https://github.com/BHoM/BHoM_Installer/issues/5

**Comment by FraserGreenroyd** [comment]
Updated milestone as too tight to fit in for the 3.0 milestone.

**Comment by al-fisher** [comment]
Discussed this already with @alelom @FraserGreenroyd as high priority for 3.2 milestone. 
To be handled as part of role out of alpha API docs
