### ISSUE TITLE
[From Google] Mobile Usability issues detected on https://bhom.xyz/

### ISSUE THREAD

**Issue by epignatelli** [BHoM/bhom.github.io#39]
|        |                                       |             |       | 
|--------|---------------------------------------|-------------|-------| 
| Status | Type                                  | Validation  | Pages | 
| Error  | Text too small to read                | Not Started | 1     | 
| Error  | Clickable elements too close together | Not Started | 1     | 
| Error  | Content wider than screen             | Not Started | 1     | 
| Valid  | Mobile-friendly pages                 | N/A         | 0     | 

I think this will affect SEO score as well.

**Comment by FraserGreenroyd** [comment]
Having rerun a lighthouse check today, these issues are not currently being reported. Other issues are, but they can be captured in subsequent issues 😄
