### ISSUE TITLE
Sample file links are to old branches - need to be updated

### ISSUE THREAD

**Issue by rwemay** [BHoM/bhom.github.io#50]
@FraserGreenroyd @al-fisher  as mentioned. I assigned Fraser, feel free to reassign!

**Comment by FraserGreenroyd** [comment]
Can we confirm what the link should point to instead? Should it just go to the `master` branch of samples or somewhere else?

**Comment by rwemay** [comment]
Technically the should point to the latest beta branch I think... which would require upgrading each time. Alternative as you suggest, could point to master branches. We run the risk of them breaking between beta installer updates then, though.
