### ISSUE TITLE
API - namespace tree

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/bhom.github.io#54]
Expand the tree on the left hand menu bar to include more levels.

**Comment by peterjamesnugent** [comment]
Could this be included in the description space too? For example the Adapters namespace could use a breakdown: https://bhom.xyz/api/object.html#!?namespace=BH.oM.Adapters

![image](https://user-images.githubusercontent.com/30078587/83145621-fcaacf00-a0ec-11ea-9e8d-53bb69d774eb.png)

**Comment by FraserGreenroyd** [comment]
Diary log entry, day 1...

Have updated the JSON creation to include navigation tree files, and updated the navigation HTML to render the navigation based on the data, regardless of how deep the tree goes. Have done this for both objects and methods. This is currently being tested on object only pages.

Things to do next:

 - [ ] Have the tree only show one level at a time until further clicked to display elements
 - [ ] Clicking the tree item should load any objects which sit at just that level
 - [ ] Clicking the engine goes to the engine, and vice versa when on the engine pages
 - [ ] Sort the trees to be alphabetical and not the random order they're currently in
 - [ ] Probably a million things that aren't yet apparent with the entire thing broken momentarily

Everything currently done is committed to branch `APIUpdates-November18` and commit has referenced this issue to track it.

Need to continue tomorrow, or when I next get a spare hour I guess given tomorrow has a ton of meetings lined up 🦆

**Comment by FraserGreenroyd** [comment]
Diary log entry, day 2...

Most of the day 1 issues are now resolved, despite meetings getting in the way.

Navigation is now fully functional and being looked at by @michaelhoehn for a first pass. Better object navigation has been put in across engines and objects in terms of display of generics and other bits and pieces which overall enhances the UX of the API documentation.

There is some issue in the data generation though, namely `Compute` methods seem to be missing entirely, but that needs investigating at the generation stage which is not this stage. But that's now tomorrow's problem...

**Comment by FraserGreenroyd** [comment]
Diary log enter, day 3...

Everything is done, the new data generation is working correctly now and including the `Compute` methods appropriately, and the errant dots have been removed from objects as appropriate. This is now ready for review so raising the PR now.
