### ISSUE TITLE
API - Highlighting entire description

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/bhom.github.io#59]
Does the entire description need to be highlighted? Given that the object is in bold I don't think it adds much and detracts from the otherwise very clean and crisp style of the documentation

![image](https://user-images.githubusercontent.com/30078587/83145006-0aac2000-a0ec-11ea-897c-2d623645623e.png)

**Comment by FraserGreenroyd** [comment]
API updates are proposed by @alelom for future workflows in line with our new documentation strategy so closing this for now in favour of those updates coming later this year.
