### ISSUE TITLE
API: Engine links for Generic objects

### ISSUE THREAD

**Issue by kThorsager** [BHoM/bhom.github.io#62]
The links for generic objects methods does not seem to appear.

Example, `PointMatrix<T>`
https://bhom.xyz/api/object.html#!?namespace=BH.oM.Data.Collections&object=PointMatrix%7BT%5D

Which only has its non generic methods linked.

i.e. `ClosestData` is not linked, etc

**Comment by FraserGreenroyd** [comment]
This has been resolved following better inclusion of generics.

![image](https://user-images.githubusercontent.com/18049174/98811831-5bed6900-2419-11eb-8491-959339e90518.png)
