### ISSUE TITLE
API - Some Excel methods are missing such as Engine.Excel.Query.CleanList()

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/bhom.github.io#65]
![image](https://user-images.githubusercontent.com/30078587/88776495-f2a15d00-d17d-11ea-98e4-c98d9abb0ccc.png)

**Comment by FraserGreenroyd** [comment]
Excel Toolkit no longer has a CleanList method, but it does have an Explode - which shows up in the API on the latest version so I'm going to close this issue as resolved.
