### ISSUE TITLE
API - Improve searches when using namespaces 

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/bhom.github.io#67]
When searching exact namespaces no results are returned. The same is true for partial namespace searches.

You could argue when searching `Engine.Reflection.Query` you could use the sidebar but both should return results.

![image](https://user-images.githubusercontent.com/30078587/88776994-a30f6100-d17e-11ea-85c6-58dc5782e04a.png)

![image](https://user-images.githubusercontent.com/30078587/88777502-321c7900-d17f-11ea-80dd-4e5fa73c533d.png)

![image](https://user-images.githubusercontent.com/30078587/88777594-4a8c9380-d17f-11ea-8bdd-3d7558c41a41.png)

**Comment by FraserGreenroyd** [comment]
API updates are proposed by @alelom for future workflows in line with our new documentation strategy so closing this for now in favour of those updates coming later this year.
